name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTQ3NGQ4YjMtYmQ1MC00NTNjLTlmMDAtN2E0YzEwNDNmMDE1IiwidGVuYW50X2lkIjoiNTRlNzEyZGQ4NGQwZjM3YWM3OWFjZGYxNDAxZGY0ZmRhZTViYmY0ZjAwNTJkODdmOGMzMjQxYTIxYWM1MWEzMyIsImludGVybmFsX3NlY3JldCI6IjUzZTQ1YTc3LWI2ZDQtNGY5OS1hMjFhLTZhN2U5ZmJlZTZkMCJ9.ES6p2iLDDLR3Mb-KeLlEMAjzjm5Di3cu7lCBbKrajnY"
JWT_SECRET = "dskddfdhfs"